apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-scaler
  template:
    metadata:
      labels:
        app: http-scaler
    spec:
      containers:
      - name: http-scaler
        image: metric-app:0.0.2 # Change this to your image name and version (defined in Makefile)
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: "0.1"
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: http-scaler
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  type: NodePort
  selector:
    app: http-scaler
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000